# Generated by Django 5.0.1 on 2024-04-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
