# Generated by Django 5.0.3 on 2024-04-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_alter_signup_password_alter_signup_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('mid_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('branch', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=20)),
                ('cgpa', models.FloatField()),
                ('tenthmarks', models.IntegerField(max_length=3)),
                ('twelfthmarks', models.IntegerField(max_length=4)),
                ('abcnumber', models.FloatField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
