# Generated by Django 5.0.3 on 2024-04-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registration_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='abcnumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mail',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mid_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tenthmarks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='twelfthmarks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.BigIntegerField(unique=True),
        ),
    ]
